// Generated by the Ballerina OpenAPI tool from specs/design/components/ceramics-api/openapi.yaml,
// then filled in by hand: every resource body below implements the documented contract.

import ballerina/http;

listener http:Listener ep0 = new (9090);

service / on ep0 {
    # Remove an item from the cart
    #
    # + return - returns can be any of following types
    # http:NoContent (Item removed)
    # http:NotFound (Cart item not found)
    resource function delete carts/[string cartId]/items/[string productId]()
            returns http:NoContent|ErrorNotFound|ErrorInternalServerError {
        boolean|error result = removeCartItemImpl(cartId, productId);
        if result is error {
            return internalError("failed to remove cart item");
        }
        if !result {
            return notFound("cart item not found");
        }
        return http:NO_CONTENT;
    }

    # Retire a product from the catalog (Store Admin only)
    #
    # + return - returns can be any of following types
    # http:NoContent (Product retired)
    # http:Unauthorized (Not signed in)
    # http:Forbidden (Caller is not a Store Admin)
    # http:NotFound (Product not found)
    resource function delete products/[string productId](@http:Header string? x\-user\-id,
            @http:Header string? x\-user\-groups)
            returns http:NoContent|ErrorUnauthorized|ErrorForbidden|ErrorNotFound|ErrorInternalServerError {
        if x\-user\-id is () {
            return unauthorized("sign-in required");
        }
        CallerRole role = resolveRole(x\-user\-id, x\-user\-groups);
        if role != ADMIN {
            return forbidden("Store Admin role required");
        }
        boolean|error result = retireProductImpl(productId);
        if result is error {
            return internalError("failed to retire product");
        }
        if !result {
            return notFound("product not found");
        }
        return http:NO_CONTENT;
    }

    # View a cart
    #
    # + return - returns can be any of following types
    # http:Ok (Cart contents)
    # http:NotFound (Cart not found)
    resource function get carts/[string cartId]() returns Cart|ErrorNotFound|ErrorInternalServerError {
        Cart?|error result = loadCart(cartId);
        if result is error {
            return internalError("failed to load cart");
        }
        if result is () {
            return notFound("cart not found");
        }
        return result;
    }

    # List orders — a signed-in shopper's own orders, or all orders for a Store Admin
    #
    # + return - returns can be any of following types
    # http:Ok (Matching orders)
    # http:Unauthorized (Not signed in)
    resource function get orders(@http:Header string? x\-user\-id, @http:Header string? x\-user\-groups,
            string? status, int 'limit = 20, int offset = 0)
            returns inline_response_200_1|ErrorUnauthorized|ErrorBadRequest|ErrorInternalServerError {
        if x\-user\-id is () {
            return unauthorized("sign-in required");
        }
        if 'limit < 1 || 'limit > 100 || offset < 0 {
            return badRequest("limit must be between 1 and 100 and offset must be non-negative");
        }
        CallerRole role = resolveRole(x\-user\-id, x\-user\-groups);
        inline_response_200_1|error result = listOrdersImpl(role, x\-user\-id, status, 'limit, offset);
        if result is error {
            return internalError("failed to list orders");
        }
        return result;
    }

    # Get a single order (owner or Store Admin only)
    #
    # + return - returns can be any of following types
    # http:Ok (Order detail)
    # http:Unauthorized (Not signed in)
    # http:Forbidden (Caller does not own this order)
    # http:NotFound (Order not found)
    resource function get orders/[string orderId](@http:Header string? x\-user\-id,
            @http:Header string? x\-user\-groups)
            returns Order|ErrorUnauthorized|ErrorForbidden|ErrorNotFound|ErrorInternalServerError {
        if x\-user\-id is () {
            return unauthorized("sign-in required");
        }
        Order?|error result = getOrderImpl(orderId);
        if result is error {
            return internalError("failed to load order");
        }
        if result is () {
            return notFound("order not found");
        }
        Order foundOrder = result;
        CallerRole role = resolveRole(x\-user\-id, x\-user\-groups);
        string? ownerCustomerId = foundOrder?.customerId;
        if role != ADMIN && ownerCustomerId != x\-user\-id {
            return forbidden("you do not own this order");
        }
        return foundOrder;
    }

    # List/search the product catalog
    #
    # + search - free-text search over name/description
    # + lowStock - admin-only filter for products at/below their low-stock threshold
    # + return - returns can be any of following types
    # http:Ok (Matching products)
    # http:BadRequest (Invalid query parameters)
    resource function get products(string? search, string? category, decimal? minPrice, decimal? maxPrice,
            boolean? lowStock, int 'limit = 20, int offset = 0)
            returns inline_response_200|ErrorBadRequest|ErrorInternalServerError {
        if 'limit < 1 || 'limit > 100 || offset < 0 {
            return badRequest("limit must be between 1 and 100 and offset must be non-negative");
        }
        inline_response_200|error result =
            listProductsImpl(search, category, minPrice, maxPrice, lowStock, 'limit, offset);
        if result is error {
            return internalError("failed to list products");
        }
        return result;
    }

    # Get a single product's details
    #
    # + return - returns can be any of following types
    # http:Ok (Product detail)
    # http:NotFound (Product not found)
    resource function get products/[string productId]() returns Product|ErrorNotFound|ErrorInternalServerError {
        Product?|error result = getProductImpl(productId);
        if result is error {
            return internalError("failed to load product");
        }
        if result is () {
            return notFound("product not found");
        }
        return result;
    }

    # Change a cart item's quantity
    #
    # + return - returns can be any of following types
    # http:Ok (Updated cart)
    # http:BadRequest (Invalid quantity or insufficient stock)
    # http:NotFound (Cart item not found)
    resource function patch carts/[string cartId]/items/[string productId](@http:Payload CartItemInput payload)
            returns Cart|ErrorBadRequest|ErrorNotFound|ErrorInternalServerError {
        CartMutationResult|error result = updateCartItemImpl(cartId, productId, payload);
        if result is error {
            return internalError("failed to update cart item");
        }
        if result.outcome == "not_found" {
            return notFound(result.message ?: "cart item not found");
        }
        if result.outcome == "bad_request" {
            return badRequest(result.message ?: "invalid quantity or insufficient stock");
        }
        Cart? cart = result.cart;
        if cart is () {
            return internalError("failed to reload cart");
        }
        return cart;
    }

    # Edit a product, including price and stock level (Store Admin only)
    #
    # + return - returns can be any of following types
    # http:Ok (Updated product)
    # http:BadRequest (Invalid product data)
    # http:Unauthorized (Not signed in)
    # http:Forbidden (Caller is not a Store Admin)
    # http:NotFound (Product not found)
    resource function patch products/[string productId](@http:Header string? x\-user\-id,
            @http:Header string? x\-user\-groups, @http:Payload ProductInput payload)
            returns Product|ErrorBadRequest|ErrorUnauthorized|ErrorForbidden|ErrorNotFound|ErrorInternalServerError {
        if x\-user\-id is () {
            return unauthorized("sign-in required");
        }
        CallerRole role = resolveRole(x\-user\-id, x\-user\-groups);
        if role != ADMIN {
            return forbidden("Store Admin role required");
        }
        if !isProductInputValid(payload) {
            return badRequest("price and stockQty must be non-negative");
        }
        Product?|error result = updateProductImpl(productId, payload);
        if result is error {
            return internalError("failed to update product");
        }
        if result is () {
            return notFound("product not found");
        }
        return result;
    }

    # Start a new cart (guest or signed-in)
    #
    # + return - Cart created
    resource function post carts(@http:Header string? x\-user\-id) returns CartCreated|ErrorInternalServerError {
        Cart|error result = createCartImpl(x\-user\-id);
        if result is error {
            return internalError("failed to create cart");
        }
        return <CartCreated>{body: result};
    }

    # Add a product to the cart, or increase its quantity
    #
    # + return - returns can be any of following types
    # http:Ok (Updated cart)
    # http:BadRequest (Invalid item or insufficient stock)
    # http:NotFound (Cart or product not found)
    resource function post carts/[string cartId]/items(@http:Payload CartItemInput payload)
            returns CartOk|ErrorBadRequest|ErrorNotFound|ErrorInternalServerError {
        CartMutationResult|error result = addCartItemImpl(cartId, payload);
        if result is error {
            return internalError("failed to update cart");
        }
        if result.outcome == "not_found" {
            return notFound(result.message ?: "cart or product not found");
        }
        if result.outcome == "bad_request" {
            return badRequest(result.message ?: "invalid item or insufficient stock");
        }
        Cart? cart = result.cart;
        if cart is () {
            return internalError("failed to reload cart");
        }
        return <CartOk>{body: cart};
    }

    # Pay for a cart's contents and create an order (guest or signed-in)
    #
    # + return - returns can be any of following types
    # http:Created (Order created and payment captured)
    # http:BadRequest (Invalid checkout request, empty cart, or insufficient stock)
    # http:PaymentRequired (Payment declined)
    # http:NotFound (Cart not found)
    resource function post checkout(@http:Header string? x\-user\-id, @http:Payload CheckoutRequest payload)
            returns OrderCreated|ErrorBadRequest|ErrorPaymentRequired|ErrorNotFound|ErrorInternalServerError {
        CheckoutResult|error result = checkoutImpl(payload, x\-user\-id);
        if result is error {
            return internalError("checkout failed");
        }
        if result.outcome == "not_found" {
            return notFound(result.message ?: "cart not found");
        }
        if result.outcome == "bad_request" {
            return badRequest(result.message ?: "invalid checkout request, empty cart, or insufficient stock");
        }
        if result.outcome == "payment_required" {
            return paymentRequired(result.message ?: "payment declined");
        }
        Order? completedOrder = result.'order;
        if completedOrder is () {
            return internalError("order missing after checkout");
        }
        return <OrderCreated>{body: completedOrder};
    }

    # Mark an order as fulfilled/shipped (Store Admin only)
    #
    # + return - returns can be any of following types
    # http:Ok (Order marked fulfilled)
    # http:Unauthorized (Not signed in)
    # http:Forbidden (Caller is not a Store Admin)
    # http:NotFound (Order not found)
    resource function post orders/[string orderId]/fulfill(@http:Header string? x\-user\-id,
            @http:Header string? x\-user\-groups)
            returns OrderOk|ErrorUnauthorized|ErrorForbidden|ErrorNotFound|ErrorInternalServerError {
        if x\-user\-id is () {
            return unauthorized("sign-in required");
        }
        CallerRole role = resolveRole(x\-user\-id, x\-user\-groups);
        if role != ADMIN {
            return forbidden("Store Admin role required");
        }
        Order?|error result = fulfillOrderImpl(orderId);
        if result is error {
            return internalError("failed to fulfill order");
        }
        if result is () {
            return notFound("order not found");
        }
        return <OrderOk>{body: result};
    }

    # Create a new product (Store Admin only)
    #
    # + return - returns can be any of following types
    # http:Created (Product created)
    # http:BadRequest (Invalid product data)
    # http:Unauthorized (Not signed in)
    # http:Forbidden (Caller is not a Store Admin)
    resource function post products(@http:Header string? x\-user\-id, @http:Header string? x\-user\-groups,
            @http:Payload ProductInput payload)
            returns ProductCreated|ErrorBadRequest|ErrorUnauthorized|ErrorForbidden|ErrorInternalServerError {
        if x\-user\-id is () {
            return unauthorized("sign-in required");
        }
        CallerRole role = resolveRole(x\-user\-id, x\-user\-groups);
        if role != ADMIN {
            return forbidden("Store Admin role required");
        }
        if !isProductInputValid(payload) {
            return badRequest("price and stockQty must be non-negative");
        }
        Product|error result = createProductImpl(payload);
        if result is error {
            return internalError("failed to create product");
        }
        return <ProductCreated>{body: result};
    }
}
