// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/constraint;
import ballerina/http;

public type Order record {
    string id;
    string? customerId?;
    "paid"|"fulfilled"|"cancelled" status;
    OrderItem[] items;
    decimal subtotal;
    decimal shippingFee;
    decimal total;
    Address shippingAddress?;
    string createdAt?;
};

public type CartItemInput record {
    string productId;
    @constraint:Int {minValue: 1}
    int quantity;
};

public type Address record {
    string line1;
    string line2?;
    string city;
    string postalCode;
    string country;
};

public type Product record {
    string id;
    string name;
    string description?;
    decimal price;
    string category?;
    int stockQty;
    # true when stock is at or below the admin-set threshold
    boolean lowStock?;
    string[] images?;
    "active"|"retired" status;
};

public type Error record {
    # HTTP or application error code
    int code;
    # short human-readable label
    string message;
    # detailed explanation
    string description?;
    # URI to documentation
    string moreInfo?;
};

public type ErrorPaymentRequired record {|
    *http:PaymentRequired;
    Error body;
|};

public type ErrorBadRequest record {|
    *http:BadRequest;
    Error body;
|};

public type CartItem record {
    string productId;
    string name?;
    decimal unitPrice?;
    int quantity;
};

public type OrderOk record {|
    *http:Ok;
    Order body;
|};

public type ProductInput record {
    string name;
    string description?;
    decimal price;
    string category?;
    int stockQty;
    string[] images?;
};

public type ErrorNotFound record {|
    *http:NotFound;
    Error body;
|};

public type OrderItem record {
    string productId;
    string name?;
    int quantity;
    decimal unitPrice;
};

public type inline_response_200_1 record {
    # total matching items
    int count;
    # relative URI of the next page
    string? next?;
    # relative URI of the previous page
    string? previous?;
    Order[] data;
};

public type inline_response_200 record {
    # total matching items
    int count;
    # relative URI of the next page
    string? next?;
    # relative URI of the previous page
    string? previous?;
    Product[] data;
};

public type CheckoutRequest record {
    string cartId;
    Address shippingAddress;
    PaymentDetails paymentDetails;
    # required for guest checkout order confirmation
    string email?;
};

public type PaymentDetails record {
    # tokenized card details from the payment provider's client-side SDK
    string paymentToken;
};

public type ErrorForbidden record {|
    *http:Forbidden;
    Error body;
|};

public type CartOk record {|
    *http:Ok;
    Cart body;
|};

public type ErrorUnauthorized record {|
    *http:Unauthorized;
    Error body;
|};

public type Cart record {
    string id;
    string? customerId?;
    CartItem[] items;
};

public type CartCreated record {|
    *http:Created;
    Cart body;
|};

public type ProductCreated record {|
    *http:Created;
    Product body;
|};

public type OrderCreated record {|
    *http:Created;
    Order body;
|};

// Not part of the documented contract — a defensive fallback for an
// unexpected failure (e.g. the database is unreachable), never used to
// signal any of the documented 400/401/402/403/404 outcomes.
public type ErrorInternalServerError record {|
    *http:InternalServerError;
    Error body;
|};
